name: CI Build
on: [ push, pull_request ]
env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and install with maven
        run: mvn install
  deploy:
    runs-on: self-hosted
    needs: build-test
    if: github.ref == 'refs/heads/main' # only run deploy on main branch
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        env: 
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: bash .github/deployment/deploy.sh